language: objective-c
before_install:
- bundle install
- rm -rf $(HOME)/Library/Developer/Xcode/DerivedData/*
- sudo gem install xcode-install
- sudo xcode-install install '7.0 beta 4'
- sudo xcode-select -s /Applications/Xcode-7.app
script: make test
notifications:
  slack:
  - secure: pbLVGeA+577zmld+ie/1KUWxin8PFB+uXogz1zrVhEqnparjbHNMvFfaAGG1gbaAJC0skGksCe+LeBrhLargbLSgAT3HrObwDCIu7H8IjaYOEhpNTHCObrwRIyOeBVHHAhjgjeElM7hvptJjRMuERErcnL65EOlaIdm4ZqOg3/0=
env:
  global:
  - ARTIFACTS_S3_BUCKET=static.cdnorigin.contentful.com
  - secure: n/hnbmOoeLt4g+Mzm6Nm/fnxwr7fFjfFTlNxEco7kk9oeNklj0vudOwbYtxL2AWuMNWX/tSHlUieKf4UGOiwzFeQmWyLdi0dkwSKRMNBNz2XQrlzjemZNf8V9+E6+JPeH8BVBKyscYgNevrp7R0Lx2h5mcDVogHm416yUiNzGOQ=
  - secure: FAIgFb/XlYTHWXAE7dzl5KFAMmST39forxsfmJdysXdaIUXK1Y44PJnS4HQ0cRa79e+o+NSOJSHLGI+qboXNoDAHqaDGBqtC7QROjW7ed0ZQp0iyNeebSq8TQzuOwdrqEjh9SGK24bgbTgQx+i8brYRJA+N8igfNtVoTUXj7buI=
  - secure: LyiQhHG89Zn0FdprFntjvT34DOcvFU/IITWhhowfgYrXGObUTEOyIyE3ve6fJpMm23B8/u1EUNxBVvqxevdGmA2RuoJiMMy+V/uFsBHmuOeJ8TeDYOgjyWJgsJt1bfDLpFwX2Ztu0smdMeuBpmsOA2I3FW0mDCx5tiAuScNidnE=
  - secure: ON4VaWtKenMkrtLpVssVMqV5AXEsH9u6DPMK5qSYMNK0rpxb5k4TBxe45UZhdZTi90l2U94EPJWriO7RaxACyuF+HL8/cREFAgRmyKRyapSxHBTkqJCJRur7RN3txzGTVQjiufhBIiXUjFCJCOC5n7laL0vNl+JinTfW6Sq3nyc=
  - secure: Tz3wMXMDIeulAbxqrPQjMgRe4ncK5fbGaDSbQYU9GxMJYdvoX5t1DpwmbbJEcVPZbpZhIHal+MnbPtTM/vry/UEclH4vepcI4Js4pCccIit15EeVbN33Yys8WB0BTeRzhQs4pNWQzwOeT+Lu4YprhUd0V0pCNIRxr7PSSex1Q0s=
